build:
  node_version: 20
  cache:
    paths:
      - frontend/node_modules
      - backend/node_modules
      - frontend/.cache
      - frontend/public
  env:
    NODE_ENV: production
    REACT_APP_API_URL: $VITE_API_URL
  npm_args: --omit=dev
  security:
    scan: true
    auto_update: true